spring.application.name=ms_movie_service

server.servlet.context-path=/api/v1
server.port=8093

spring.data.mongodb.uri=${MONGO_URI}
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}
aws.sessionToken=${AWS_SESSION_TOKEN_KEY}
aws.region=${AWS_REGION}
aws.s3.bucket=${S3_BUCKET}
tmdb.token=${TMDB_TOKEN}
movies.count=${MOVIES_COUNT}
logging.file.name=logs/MovieSphereLogs/movie-service.log
